/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminResponse {
  'principal' : Principal,
  'isSuperAdmin' : boolean,
}
export interface Candidate {
  'lastQualification' : string,
  'dateOfBirth' : string,
  'createdAt' : bigint,
  'fullName' : string,
  'fatherName' : string,
  'address' : string,
  'admissionID' : string,
  'mobile' : string,
  'photo' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem { 'description' : string, 'image' : ExternalBlob }
export interface NewsItem {
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
}
export type SubmitAdmissionFormError = { 'invalidMobileNumber' : null } |
  { 'mobileAlreadyRegistered' : string };
export type SubmitAdmissionFormResult = { 'ok' : string } |
  { 'err' : SubmitAdmissionFormError };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdmin' : ActorMethod<[Principal], boolean>,
  'addGalleryItem' : ActorMethod<[ExternalBlob, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNewsItem' : ActorMethod<[string, string, bigint], undefined>,
  'deleteGalleryItem' : ActorMethod<[string], undefined>,
  'deleteNewsItem' : ActorMethod<[string], undefined>,
  'editNewsItem' : ActorMethod<[string, string, bigint], undefined>,
  'getAdmins' : ActorMethod<[], Array<AdminResponse>>,
  'getAllCandidates' : ActorMethod<[], Array<Candidate>>,
  'getAllNewsItems' : ActorMethod<[], Array<NewsItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateByMobile' : ActorMethod<[string], [] | [Candidate]>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSuperAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAdmin' : ActorMethod<[Principal], boolean>,
  'resetAdminSystemForce' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAdmissionForm' : ActorMethod<
    [string, string, string, string, string, string, [] | [ExternalBlob]],
    SubmitAdmissionFormResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];