/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminResponse = IDL.Record({
  'principal' : IDL.Principal,
  'isSuperAdmin' : IDL.Bool,
});
export const Candidate = IDL.Record({
  'lastQualification' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'createdAt' : IDL.Int,
  'fullName' : IDL.Text,
  'fatherName' : IDL.Text,
  'address' : IDL.Text,
  'admissionID' : IDL.Text,
  'mobile' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const NewsItem = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GalleryItem = IDL.Record({
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const SubmitAdmissionFormError = IDL.Variant({
  'invalidMobileNumber' : IDL.Null,
  'mobileAlreadyRegistered' : IDL.Text,
});
export const SubmitAdmissionFormResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : SubmitAdmissionFormError,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'addGalleryItem' : IDL.Func([ExternalBlob, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNewsItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
  'deleteNewsItem' : IDL.Func([IDL.Text], [], []),
  'editNewsItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
  'getAdmins' : IDL.Func([], [IDL.Vec(AdminResponse)], ['query']),
  'getAllCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
  'getAllNewsItems' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateByMobile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Candidate)],
      ['query'],
    ),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSuperAdmin' : IDL.Func([], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'resetAdminSystemForce' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAdmissionForm' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [SubmitAdmissionFormResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminResponse = IDL.Record({
    'principal' : IDL.Principal,
    'isSuperAdmin' : IDL.Bool,
  });
  const Candidate = IDL.Record({
    'lastQualification' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'createdAt' : IDL.Int,
    'fullName' : IDL.Text,
    'fatherName' : IDL.Text,
    'address' : IDL.Text,
    'admissionID' : IDL.Text,
    'mobile' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const NewsItem = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GalleryItem = IDL.Record({
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const SubmitAdmissionFormError = IDL.Variant({
    'invalidMobileNumber' : IDL.Null,
    'mobileAlreadyRegistered' : IDL.Text,
  });
  const SubmitAdmissionFormResult = IDL.Variant({
    'ok' : IDL.Text,
    'err' : SubmitAdmissionFormError,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'addGalleryItem' : IDL.Func([ExternalBlob, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNewsItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
    'deleteNewsItem' : IDL.Func([IDL.Text], [], []),
    'editNewsItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
    'getAdmins' : IDL.Func([], [IDL.Vec(AdminResponse)], ['query']),
    'getAllCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
    'getAllNewsItems' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateByMobile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Candidate)],
        ['query'],
      ),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSuperAdmin' : IDL.Func([], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'resetAdminSystemForce' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAdmissionForm' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [SubmitAdmissionFormResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };